stages:
    - run-checks

checks:
    image: node:latest
    stage: run-checks
    before_script:
        - echo "running yarn install"
        - cd app/metais-portal && yarn install
    script:
        - yarn run typescript-check
        - cd app/metais-portal && yarn run lint
