stages:
    - run-checks

checks:
    image: node:latest
    stage: run-checks
    before_script:
        - echo "running yarn install"
        - yarn install
    script:
        - npx nx run-many -t metais-admin metais-portal typescript-check
        - npx nx run-many -t metais-admin metais-portal lint
