cache: 
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

variables:
  APP_PATH: '$CI_PROJECT_DIR'

stages:
    - run-checks
    - build-node
    - build-docker
    - deploy-okd-feature
    - deploy-okd-develop
    - deploy

checks:
    image: nexus.isdd.sk:8490/node:latest
    stage: run-checks
    before_script:
        - echo "running yarn install"
        - yarn install
    script:
        - yarn run typescript-check
        - yarn run lint


build-node:
    image: nexus.isdd.sk:8490/node:latest
    stage: build-node
    script:
        - yarn run build
    artifacts:
        expire_in: 2 days
        paths:
            - 'app/metais-portal/dist/'
            - 'app/metais-admin/dist/'
    when: manual


build-docker:
    image: nexus.isdd.sk:8490/docker:20.10-git
    stage: build-docker
    services:
        - name: nexus.isdd.sk:8490/docker:dind
          alias: docker
    variables:
        DOCKER_HOST: tcp://docker:2375
    script:
        - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
        # build portal
        - docker build -f docker/Dockerfile --build-arg BUILD_DIR=app/metais-portal/dist/ -t ${CI_REGISTRY_IMAGE}/portal .
        #- docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG#v}
        - docker push ${CI_REGISTRY_IMAGE}/portal:latest
        # build admin
        - docker build -f docker/Dockerfile --build-arg BUILD_DIR=app/metais-admin/dist/ -t ${CI_REGISTRY_IMAGE}/admin .
        #- docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG#v}
        - docker push ${CI_REGISTRY_IMAGE}/portal:latest
    when: manual

deploy-okd-feature:
    stage: deploy-okd-feature
    image: gitlab.isdd.sk:4567/isdd-docker/okd/alpine:1-2-0
    script:
        - curl -X POST --fail -F token=$CD_REPO_TOKEN -F ref=$BRANCH_NAME --form "variables[HELM_RELEASE_NAME]=$RELEASE_NAME" --form "variables[OKD_HELM_OPTS]=$OKD_HELM_OPTS" https://gitlab.isdd.sk/api/v4/projects/967/trigger/pipeline
    rules:
        - if: $CI_COMMIT_REF_NAME =~ /^feature-.+$/
          when: manual

deploy-okd-develop:
    stage: deploy-okd-develop
    image: gitlab.isdd.sk:4567/isdd-docker/okd/alpine:1-2-0
    script:
        - curl -X POST --fail -F token=$CD_REPO_TOKEN -F ref=$BRANCH_NAME --form "variables[HELM_RELEASE_NAME]=$RELEASE_NAME" https://gitlab.isdd.sk/api/v4/projects/967/trigger/pipeline
    rules:
        - if: $CI_COMMIT_REF_NAME =~ /^develop+$/
          when: manual

deploy-azure-portal:
    image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
    variables:
        API_TOKEN: $PORTAL_DEPLOYMENT_TOKEN
        OUTPUT_PATH: '$CI_PROJECT_DIR/app/metais-portal/dist/'
    stage: deploy
    script:
        - echo "MetaIS Portal deployed successfully."
    when: manual
    
deploy-azure-admin:
    image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
    variables:
        API_TOKEN: $ADMIN_DEPLOYMENT_TOKEN
        OUTPUT_PATH: '$CI_PROJECT_DIR/app/metais-admin/dist/'
    stage: deploy
    script:
        - echo "MetaIS Admin deployed successfully."
    when: manual
