/* eslint-disable no-restricted-imports */

export { default as HomeIcon } from './home.svg'
export { default as DotsIcon } from './dots.svg'
export { default as PaginatorEndArrowIcon } from './paginator-end-arrow.svg'
export { default as PaginatorRightArrowIcon } from './paginator-right-arrow.svg'
export { default as PaginatorLeftArrowIcon } from './paginator-left-arrow.svg'
export { default as PaginatorStartArrowIcon } from './paginator-start-arrow.svg'
export { default as CircleLoadingArrowIcon } from './circle-loading-arrow.svg'
export { default as LoadingArrowIcon } from './loading-arrow.svg'
export { default as ArrowDownIcon } from './arrow-down.svg'
export { default as NotificationIcon } from './notification-icon.svg'
export { default as FactCheckIcon } from './fact-check.svg'
export { default as LogoMirri } from './logo-mirri.svg'
export { default as RoundCheckGreenIcon } from './round-check-green.svg'
export { default as ImportDeleteIcon } from './delete-import.svg'
export { default as ErrorTriangleIcon } from './error-triangle.svg'
export { default as CloseIcon } from './close-icon.svg'
export { default as ProfileIcon } from '@id-sk/frontend/idsk/assets/images/header-web/profile.svg'
export { default as ExportIcon } from './export-icon.svg'
export { default as NavigationCloseIcon } from './navigation-close.svg'
export { default as ImportIcon } from './import-icon.svg'
export { default as PlusIcon } from './plus-icon.svg'
export { default as ChangeIcon } from './change-icon.svg'
export { default as CheckInACircleIcon } from './check-in-a-circle-icon.svg'
export { default as CrossInACircleIcon } from './cross-in-a-circle-icon.svg'
