import { ColumnDef } from '@tanstack/react-table'
import React from 'react'

import { CheckBox } from '../CheckBox'

export type Table = {
    nazov: React.ReactNode
    kod: React.ReactNode
    sluzba: React.ReactNode
    elek: React.ReactNode
    evidencia: React.ReactNode
}

export const placeholderColumns: ColumnDef<Table>[] = [
    {
        accessorFn: (row) => row.nazov,
        header: () => (
            <>
                <CheckBox label="" name="hi" id="hi" value="hi" />
                <div className="th-span" draggable="true">
                    koncova sluzba
                </div>
            </>
        ),
        id: '1',
        cell: (row) => <CheckBox label={row.getValue() as string} name="hi" id="hi" value="hi" />,
    },
    {
        accessorFn: (row) => row.kod,
        header: 'Kod MetaIS',
        id: '2',
        cell: (row) => <strong>{row.getValue() as string}</strong>,
    },
    {
        header: 'Typ sluzby',
        id: '3',
        accessorKey: 'sluzba',
    },
    {
        header: 'Uroven elek sluzby',
        id: '4',
        accessorFn: (row) => row.elek,
        cell: (row) => <a href="#">{row.getValue() as string}</a>,
    },
    {
        accessorFn: (row) => row.evidencia,
        header: 'Stav evidencie',
        id: '5',
        cell: (row) => (row.getValue() === 'nevytvorene' ? <p style={{ color: 'red' }}>{row.getValue() as string}</p> : row.getValue()),
    },
]

export const placeholderData: Table[] = [
    {
        nazov: 'asd',
        kod: '1235',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '145',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'nevytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'nevytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
]
