export enum RouteNames {
    HOME = '/',
    DEV_TEST_SCREEN = 'DevTestScreen',
    PROJEKT_LIST_PAGE = '/projekt/list',
    PROJEKT_ENTITY_DETAIL = '/ci/:entityName/:projektId',
    HOW_TO_EGOV_COMPONENTS = 'howto/CMDB.EGOV_TITLE/EGOV_HOWTO',
    HOW_TO_STANDARDIZATION = 'howto/STANDARD.PROCESS/STD_HOWTO',
    HOW_TO_MONITORING = 'howto/MONITORING.MONITORING/MONITORING_HOWTO',
    //not found on metais
    HOW_TO_DATA_OBJECTS = 'howto/DATA.DATA_OBJECTS/DO_HOWTO',
    PREHLADY_A_POSTUPY = '',
    DOCUMENTS_LIST_TAB = '/ci/:entityName/:entityId/documents',
    RELATIONSHIPS_LIST_TAB = '/ci/:entityName/:entityId/relationships',
    LOGIN = 'login',
}

export enum NavigationSubRoutes {
    CIEL = 'ci/Ciel',
    PROGRAM = 'ci/Program',
    KONCOVE_SLUZBY = 'ci/ks',
    APLIKACNE_SLUZBY = 'ci/AS',
    ISVS = 'ci/ISVS',
    INFRASCTRUCTURES = 'ci/InfraSluzba',
    AUTORITY = 'ci/PO_IS',
    OTHER_COMPONENT = '',
    STANDARDY_ISVS = 'publicspace',
    OSOBITNE_POSTUPY = 'ci/osobitny_postup_ITVS',
    KOMISIA_NA_STANDARDIZACIU = 'standardization/groupdetail/a89f40e5-7917-46d4-9ba1-0c6eae2a5e25',
    PRACOVNE_SKUPINY_KOMISIE = 'standardization/groupslist',
    TVORBA_NAVRHU = 'standardization/newdraft',
    REFERENCE_REGISTRE = 'refregisters/list',
    CISELNIKY = 'codelists/publiclist',
    CENTRALNY_DATOVY_MODEL = '',
    PRUD = '',
    JEDNOTNA_DIGITALNA_BRANA = '',
    PREHLADY = '',
    MONITORING_KS = 'monitorks',
    MONITORING_AS = 'monitoras',
    MONITORING_PARAMETRE_SET = 'monitor-report',
}
