import { ApiAttachment } from '@isdd/metais-common/api/generated/standards-swagger'
import { TFunction } from 'i18next'
import * as yup from 'yup'

export const generateSchemaForCreateDraft = (t: TFunction<'translation', undefined, 'translation'>) => {
    return yup.object().shape({
        srName: yup.string().required(t('validation.required')),
        srDescription1: yup.string().required(t('validation.required')),
        attachments: yup.array<ApiAttachment>(),
        proposalDescription2: yup.string(),
        proposalDescription3: yup.string(),
        impactDescription1: yup.string(),
        impactDescription5: yup.string(),
        impactDescription7: yup.string(),
        links: yup.array().of(
            yup.object().shape({
                linkDescription: yup.string().required(t('validation.required')),
                url: yup.string().required(t('validation.required')),
                linkType: yup.string(),
                linkSize: yup.string(),
                name: yup.string(),
                id: yup.number(),
                type: yup.string(),
            }),
        ),
        version: yup.number(),
        name: yup.string(),
        email: yup.string(),
        actionDesription: yup.string(),
        srDescription2: yup.string(),
        srDescription3: yup.string(),
        srDescription4: yup.string(),
        srDescription5: yup.string(),
        srDescription6: yup.string(),
        proposalDescription1: yup.string(),
        applicabilityDescription1: yup.string(),
        applicabilityDescription2: yup.string(),
        applicabilityDescription3: yup.string(),
        applicabilityDescription4: yup.string(),
        relevanceDescription1: yup.string(),
        adaptabilityDescription1: yup.string(),
        adaptabilityDescription2: yup.string(),
        impactDescription2: yup.string(),
        impactDescription3: yup.string(),
        impactDescription4: yup.string(),
        impactDescription6: yup.string(),
        impactDescription8: yup.string(),
        impactDescription9: yup.string(),
        impactDescription10: yup.string(),
        impactDescription11: yup.string(),
        impactDescription12: yup.string(),
        scalabilityDescription1: yup.string(),
        expandabilityDescription1: yup.string(),
        expandabilityDescription2: yup.string(),
        stabilityDescription1: yup.string(),
        stabilityDescription2: yup.string(),
        stabilityDescription3: yup.string(),
        maintenanceDescription1: yup.string(),
        outputsDescription1: yup.string(),
        outputsDescription2: yup.string(),
        outputsDescription3: yup.string(),
        outputsDescription4: yup.string(),
        outputsDescription5: yup.string(),
        processDescription1: yup.string(),
        processDescription2: yup.string(),
        processDescription3: yup.string(),
        processDescription4: yup.string(),
        processDescription5: yup.string(),
        processDescription6: yup.string(),
        extensionDescription1: yup.string(),
        extensionDescription2: yup.string(),
        extensionDescription3: yup.string(),
        extensionDescription4: yup.string(),
        extensionDescription5: yup.string(),
        extensionDescription6: yup.string(),
        extensionDescription7: yup.string(),
        maturityDescription1: yup.string(),
        maturityDescription2: yup.string(),
        maturityDescription3: yup.string(),
        reusabilityDescription1: yup.string(),
        reusabilityDescription2: yup.string(),
    })
}
