export const placeholderColumns = [
    {
        header: 'Nazov koncovej sluzby',
        id: '1',
        accessorKey: 'nazov',
    },
    {
        header: 'Kod MetaIS',
        id: '2',
        accessorKey: 'kod',
    },
    {
        header: 'Typ sluzby',
        id: '3',
        accessorKey: 'sluzba',
    },
    {
        header: 'Uroven elek sluzby',
        id: '4',
        accessorKey: 'elek',
    },
    {
        header: 'Stav evidencie',
        id: '5',
        accessorKey: 'evidencia',
    },
]

export const placeholderData = [
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 1',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 2',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 3',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 4',
        evidencia: 'vytvorene',
    },
    {
        nazov: 'podanie ziadosti',
        kod: '12345',
        sluzba: 'statna sprava...',
        elek: 'uroven 5',
        evidencia: 'vytvorene',
    },
]
